config/routes.rb
Clarion::Application.routes.draw do
  resources :habitaciones

  get "habitaciones/index"

  get "home/index"

   root :to => 'home#index'

end

app/models/habitacione.rb
class Habitacione < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/habitaciones_controller.rb
class HabitacionesController < ApplicationController
  # GET /habitaciones
  # GET /habitaciones.json
  def index
    @habitaciones = Habitacione.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @habitaciones }
    end
  end

  # GET /habitaciones/1
  # GET /habitaciones/1.json
  def show
    @habitacione = Habitacione.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @habitacione }
    end
  end

  # GET /habitaciones/new
  # GET /habitaciones/new.json
  def new
    @habitacione = Habitacione.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @habitacione }
    end
  end

  # GET /habitaciones/1/edit
  def edit
    @habitacione = Habitacione.find(params[:id])
  end

  # POST /habitaciones
  # POST /habitaciones.json
  def create
    @habitacione = Habitacione.new(params[:habitacione])

    respond_to do |format|
      if @habitacione.save
        format.html { redirect_to @habitacione, notice: 'Habitacione was successfully created.' }
        format.json { render json: @habitacione, status: :created, location: @habitacione }
      else
        format.html { render action: "new" }
        format.json { render json: @habitacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /habitaciones/1
  # PUT /habitaciones/1.json
  def update
    @habitacione = Habitacione.find(params[:id])

    respond_to do |format|
      if @habitacione.update_attributes(params[:habitacione])
        format.html { redirect_to @habitacione, notice: 'Habitacione was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @habitacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habitaciones/1
  # DELETE /habitaciones/1.json
  def destroy
    @habitacione = Habitacione.find(params[:id])
    @habitacione.destroy

    respond_to do |format|
      format.html { redirect_to habitaciones_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habitaciones_helper.rb
module HabitacionesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/habitaciones/_form.html.erb
<%= form_for(@habitacione) do |f| %>
  <% if @habitacione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@habitacione.errors.count, "error") %> prohibited this habitacione from being saved:</h2>

      <ul>
      <% @habitacione.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/habitaciones/edit.html.erb
<h1>Editing habitacione</h1>

<%= render 'form' %>

<%= link_to 'Show', @habitacione %> |
<%= link_to 'Back', habitaciones_path %>

app/views/habitaciones/new.html.erb
<h1>New habitacione</h1>

<%= render 'form' %>

<%= link_to 'Back', habitaciones_path %>

app/views/habitaciones/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_habitacione_path(@habitacione) %> |
<%= link_to 'Back', habitaciones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clarion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>